import { chromium } from 'playwright-core'
const S = process.argv[2]
const b = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', headless: true })
const p = await b.newPage({ viewport: { width: 1440, height: 900 } })
const errs = []
p.on('pageerror', e => errs.push('pageerror ' + e.message))
p.on('console', m => { if (m.type() === 'error') errs.push('console ' + m.text().slice(0, 160)) })
await p.goto('http://localhost:3000/chapter1', { waitUntil: 'networkidle', timeout: 90000 })
await p.waitForTimeout(2500)
await p.screenshot({ path: `${S}/new-entry.png` })
await p.screenshot({ path: `${S}/new-entry-full.png`, fullPage: true })
console.log('entry title:', await p.title(), '· h1:', await p.textContent('h1'), '· stops:', await p.$$eval('.chapter-menu-nav a', a => a.length))
console.log('start button:', await p.$eval('.p1-entry-actions .is-primary', b => b.textContent.trim() + ' disabled=' + b.disabled))
await p.goto('http://localhost:3000/chapter1/end', { waitUntil: 'networkidle', timeout: 90000 })
await p.waitForTimeout(2500)
console.log('end: film present?', !!(await p.$('.ch1-film')))
await p.screenshot({ path: `${S}/new-end-film.png` })
const skip = await p.$('.ch1-film button:has-text("דלג")')
if (skip) { await skip.click(); await p.waitForTimeout(1500) }
await p.screenshot({ path: `${S}/new-end.png` })
await p.screenshot({ path: `${S}/new-end-full.png`, fullPage: true })
console.log('end h1:', await p.textContent('h1'), '· sections:', await p.$$eval('.article-section', a => a.length))
await p.goto('http://localhost:3000/chapter1/play', { waitUntil: 'domcontentloaded', timeout: 90000 })
await p.waitForFunction(() => !!window.__ch1Live, null, { timeout: 120000 }).catch(() => console.log('play: __ch1Live not found'))
console.log('play mounted:', await p.evaluate(() => !!window.__ch1Live), '· url:', p.url())
await p.goto('http://localhost:3000/chapter1?region=mecca&from=test', { waitUntil: 'domcontentloaded', timeout: 90000 })
await p.waitForTimeout(4000)
console.log('old deep link →', p.url())
console.log('errors:', errs.length, errs.slice(0, 5))
await b.close()
