import { chromium } from 'playwright-core'
const b = await chromium.launch({ channel: 'chrome', headless: true })
const page = await (await b.newContext({ viewport: { width: 1500, height: 1000 } })).newPage()
await page.goto('http://localhost:3000/chapter4', { waitUntil: 'domcontentloaded', timeout: 180000 })
await page.waitForTimeout(9000)
const st = await page.$('.ch4-stage.is-wide')
await st?.scrollIntoViewIfNeeded(); await page.waitForTimeout(1000)
await st?.screenshot({ path: 'scratchpad/stage2-wide.png' })
const dots = await page.$$('.ch4-stage.is-wide .ch4-stage-dot')
await dots[4]?.click(); await page.waitForTimeout(900)
await st?.screenshot({ path: 'scratchpad/stage2-wide5.png' })
const ins = await page.$('.ch4-stage.is-inset')
await ins?.scrollIntoViewIfNeeded(); await page.waitForTimeout(900)
await ins?.screenshot({ path: 'scratchpad/stage2-inset.png' })
console.log('shot')
await b.close()
