import { chromium } from 'playwright-core'
const browser = await chromium.launch({ channel: 'chrome', headless: false })
const page = await (await browser.newContext({ viewport: { width: 1100, height: 800 } })).newPage()
await page.goto('http://localhost:3000/chapter1/dev-character?model=%2Fassets%2Fchapter1%2Fmodels%2Fp3walkonly.glb&raw=1', { waitUntil: 'domcontentloaded' })
await page.waitForTimeout(6000)
// הקליפ היחיד — הכפתור הראשון בשורת הקליפים (השם הגולמי של Meshy)
await page.evaluate(() => {
  const btns = [...document.querySelectorAll('button')].filter((b) => !['low','back','side','far','front'].includes(b.textContent.trim()))
  btns[0]?.click()
})
await page.waitForTimeout(2500)
await page.click('text=far').catch(() => {})
await page.waitForTimeout(1800)
await page.screenshot({ path: 'scratchpad/committee-r0/p3-single-far.png' })
await page.click('text=front').catch(() => {})
await page.waitForTimeout(1800)
await page.screenshot({ path: 'scratchpad/committee-r0/p3-single-front.png' })
await browser.close()
console.log('done')
